[package]
name = "log-looker"
version = "0.1.0"
description = "Fetch, cache and cross-search log files from pluggable sources"
authors = ["Daniel Vazac"]
edition = "2021"
license = "MIT"
repository = "https://github.com/PsyChonek/LogLooker"

[lib]
name = "log_looker_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = { version = "0.4", features = ["serde"] }
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls", "stream", "gzip"] }
tokio = { version = "1", features = ["full"] }
futures-util = "0.3"
regex = "1"
rayon = "1"
zstd = "0.13"
dirs = "6"
fancy-regex = "0.18.0"

[profile.release]
lto = true
opt-level = "s"
panic = "abort"
strip = true
codegen-units = 1
