<#
.SYNOPSIS
Regenerates the winget manifests in winget/ from built MSIs.

.DESCRIPTION
Reads each MSI's SHA256 and ProductCode out of the file itself rather than
having them typed in, then writes all three manifests. The ProductCode changes
with every bundle identifier or version change, which is exactly the kind of
thing that goes stale when it is maintained by hand.

.PARAMETER Version
Version being released, without the 'v' prefix. Defaults to the version in
package.json.

.PARAMETER ArtifactsPath
Folder holding the MSIs. Defaults to Tauri's own output directory.

.EXAMPLE
./scripts/update-winget-manifests.ps1

.EXAMPLE
./scripts/update-winget-manifests.ps1 -Version 1.2.0 -ArtifactsPath release-artifacts
#>
param(
    [Parameter(Mandatory = $false)]
    [string]$Version,

    [Parameter(Mandatory = $false)]
    [string]$ArtifactsPath = "src-tauri/target/release/bundle/msi"
)

$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
Set-Location $Root

if (-not $Version) {
    $Version = (Get-Content "package.json" -Raw | ConvertFrom-Json).version
}
$AppName = (Get-Content "src-tauri/tauri.conf.json" -Raw | ConvertFrom-Json).productName
$Tag = "v$Version"

Write-Host "Extracting MSI metadata for winget manifests ($AppName $Version)..." -ForegroundColor Cyan

if (-not (Test-Path $ArtifactsPath)) {
    Write-Error "Artifacts directory '$ArtifactsPath' not found. Build first: npm run tauri build"
    exit 1
}

# Only this version's MSIs: the bundle directory keeps every past build
$msiFiles = Get-ChildItem -Path $ArtifactsPath -Filter "*.msi" |
    Where-Object { $_.Name -like "*_${Version}_*" }

if ($msiFiles.Count -eq 0) {
    Write-Error "No MSI for version $Version in $ArtifactsPath"
    exit 1
}

$manifest = @{}

foreach ($msi in $msiFiles) {
    Write-Host "Processing: $($msi.Name)" -ForegroundColor Yellow

    $sha256 = (Get-FileHash $msi.FullName -Algorithm SHA256).Hash
    Write-Host "  SHA256: $sha256"

    $arch = if ($msi.Name -match 'arm64') { 'arm64' } else { 'x64' }

    # ProductCode straight out of the MSI's Property table. A guess here would
    # make winget unable to tell an installed package from an absent one.
    $productCode = $null
    try {
        $installer = New-Object -ComObject WindowsInstaller.Installer
        $database = $installer.GetType().InvokeMember(
            "OpenDatabase", "InvokeMethod", $null, $installer, @($msi.FullName, 0))
        $view = $database.GetType().InvokeMember(
            "OpenView", "InvokeMethod", $null, $database,
            @("SELECT Value FROM Property WHERE Property='ProductCode'"))
        $view.GetType().InvokeMember("Execute", "InvokeMethod", $null, $view, $null)
        $record = $view.GetType().InvokeMember("Fetch", "InvokeMethod", $null, $view, $null)
        if ($record) {
            $productCode = $record.GetType().InvokeMember(
                "StringData", "GetProperty", $null, $record, @(1))
        }
        $view.GetType().InvokeMember("Close", "InvokeMethod", $null, $view, $null)
    } catch {
        Write-Error "Could not read ProductCode from $($msi.Name): $_"
        exit 1
    }
    if (-not $productCode) {
        Write-Error "ProductCode is empty in $($msi.Name)"
        exit 1
    }

    Write-Host "  ProductCode: $productCode"
    $manifest[$arch] = @{ sha256 = $sha256; productCode = $productCode; filename = $msi.Name }
}

Write-Host "Writing manifests..." -ForegroundColor Cyan
New-Item -ItemType Directory -Path "winget" -Force | Out-Null

# 1. Version manifest
$versionFile = "winget/PsyChonek.LogLooker.yaml"
@"
# yaml-language-server: `$schema=https://aka.ms/winget-manifest.version.1.12.0.schema.json

PackageIdentifier: PsyChonek.LogLooker
PackageVersion: $Version
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.12.0
"@ | Set-Content -Path $versionFile -Encoding utf8

# 2. Installer manifest
$installerFile = "winget/PsyChonek.LogLooker.installer.yaml"
$installerYaml = @"
# yaml-language-server: `$schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
#
# Generated by scripts/update-winget-manifests.ps1 - the SHA256 and ProductCode
# are read out of the built MSIs rather than typed.

PackageIdentifier: PsyChonek.LogLooker
PackageVersion: $Version
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallModes:
- silent
- silentWithProgress
InstallerType: wix
Scope: machine
Installers:
"@

foreach ($arch in @('x64', 'arm64')) {
    if (-not $manifest[$arch]) { continue }
    $installerYaml += @"

- Architecture: $arch
  InstallerUrl: https://github.com/PsyChonek/LogLooker/releases/download/$Tag/$($manifest[$arch].filename)
  InstallerSha256: $($manifest[$arch].sha256)
  ProductCode: '$($manifest[$arch].productCode)'
"@
}

$installerYaml += "`nManifestType: installer`nManifestVersion: 1.12.0`n"
Set-Content -Path $installerFile -Value $installerYaml -Encoding utf8

# 3. Locale manifest
$localeFile = "winget/PsyChonek.LogLooker.locale.en-US.yaml"
@"
# yaml-language-server: `$schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: PsyChonek.LogLooker
PackageVersion: $Version
PackageLocale: en-US
Publisher: PsyChonek
PublisherUrl: https://github.com/PsyChonek
PublisherSupportUrl: https://github.com/PsyChonek/LogLooker/issues
Author: PsyChonek
PackageName: LogLooker
PackageUrl: https://github.com/PsyChonek/LogLooker
License: MIT
LicenseUrl: https://github.com/PsyChonek/LogLooker/blob/main/LICENSE
ShortDescription: Fetch, cache and cross-search log files from many services at once
Description: >-
  LogLooker downloads only the log files a date range needs, caches them compressed,
  and searches every selected service in one merged timeline with substring or full
  regex queries. Results can be charted over time or ranked by category, aggregating
  the whole result rather than the loaded page. Where the logs come from, how they
  are laid out, how their lines parse and what is worth searching are described by
  plugins - one JSON file each, no code. Two ship with the app: a local folder reader
  that needs no credentials, and an Azure App Service reader that authenticates with
  the Azure CLI.
Tags:
- log
- logs
- log-viewer
- log-analysis
- search
- regex
- azure
- devops
- tauri
- vue
ReleaseNotes: 'Version $Version release.'
ReleaseNotesUrl: https://github.com/PsyChonek/LogLooker/releases/tag/$Tag
ManifestType: defaultLocale
ManifestVersion: 1.12.0
"@ | Set-Content -Path $localeFile -Encoding utf8

Write-Host "Manifests written:" -ForegroundColor Green
Write-Host "  - $versionFile"
Write-Host "  - $installerFile"
Write-Host "  - $localeFile"
Write-Host ""
Write-Host "Validate the three YAML files in an empty directory with: winget validate --manifest <directory>" -ForegroundColor Gray
Write-Host "Submit with:   ./scripts/submit-to-winget.ps1 -Version $Version" -ForegroundColor Gray
